version: "3.0"
services:
  pub1: 
    build: .
    image: sub-im
    environment:
      HOST: research.upb.edu
      TOPIC: node/ds
      PORT: 21242
  pub2:
    image: sub-im
    environment:
      HOST: research.upb.edu
      TOPIC: node/ds
      PORT: 21242
    depends_on:
      - pub1
  pub3:
    image: sub-im
    environment:
      HOST: research.upb.edu
      TOPIC: node/ds
      PORT: 21242
    depends_on:
      - pub1
  pub4:
    image: sub-im
    environment:
      HOST: research.upb.edu
      TOPIC: node/ds
      PORT: 21242
    depends_on:
      - pub1
  pub5:
    image: sub-im
    environment:
      HOST: research.upb.edu
      TOPIC: node/ds
      PORT: 21242
    depends_on:
      - pub1