version: "3.9"
services:
  # BROKER SERVICE ---------------------------------------------
  broker:
    image: eclipse-mosquitto:latest
    # General configuration --------------
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    #networks:
      #- dsnet
    # Deployment configuration -----------
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
  # PUBLISHER SERVICE ------------------------------------------
  publisher:
    image: 10.1.2.122:5000/nodejs
    build: ../Publisher
    # General configuration --------------
    #networks:
      #- dsnet
    env_file:
      - pub.env
    # Deployment configuration -----------
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
  # SUBSCRIBER SERVICE -----------------------------------------
  subscriber:
    image: 10.1.2.122:5000/subscriber
    build: ../Subscriber
    # General configuration --------------
    env_file:
      - sub.env
    # Deployment configuration
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==worker"
#networks:
#  dsnet:
#    name: ds-net
#    driver: bridge
