version: "3.9"
services:
  # BROKER SERVICE ---------------------------------------------
  broker:
    image: eclipse-mosquitto:latest
    # General configuration --------------
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - dsnet
    # Deployment configuration -----------
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
  # PUBLISHER SERVICE ------------------------------------------
  publisher:
    image: nodejs
    # General configuration --------------
    networks:
      - dsnet
    env_file:
      - pub.env
    # Deployment configuration -----------
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
  # SUBSCRIBER SERVICE -----------------------------------------
  subscriber:
    image: subscriber
    # General configuration --------------
    env_file:
      - sub.env
    # Deployment configuration
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==worker"
networks:
  dsnet:
    name: ds-net
    driver: bridge
